### ISSUE TITLE
Base URI and Nginx

### ISSUE THREAD

**Issue by devster31** [jfurrow/flood#411]
The objective is to access `flood` from `domain.tld/flood`.
Below my current config:
```yml
# docker-compose.yml
...
  flood:
    build:
      context: flood
    environment:
      - "FLOOD_BASE_URI=${FLOOD_BASE_URI:-/}"
      - "FLOOD_SECRET=${FLOOD_SECRET}"
      - "RTORRENT_SCGI_HOST=${RTORRENT_SCGI_HOST:-127.0.0.1}"
      - "RTORRENT_SCGI_PORT=${RTORRENT_SCGI_PORT:-5000}"
      - "RTORRENT_SOCK=${RTORRENT_SOCK:-false}"
      - "FLOOD_ENABLE_SSL=${FLOOD_ENABLE_SSL:-false}"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - "./data/flood:/data"
...
```
With this variable `FLOOD_BASE_URI=/flood/`
```
...
server {
    listen 443 ssl http2 default_server;
    server_name domain.tld;
    root /var/www;
    index index.php index.html index.htm;

    ssl on;
    ssl_certificate     /etc/letsencrypt/live/domain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.tld/privkey.pem;
...
    location /flood/ {
        proxy_pass http://localhost:3000/;
    }
...
```
And here the logs:
```apache
# flood container
flood_1  | > flood@1.0.0 start /usr/src/app
flood_1  | > node server/bin/www
flood_1  |
flood_1  | GET / 200 314.683 ms - 668

# nginx access.log
IP - - [25/Jul/2017:23:38:29 +0200] "GET /flood/ HTTP/1.1" 200 403 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3159.5 Safari/537.36"
IP - - [25/Jul/2017:23:38:29 +0200] "GET /flood/style.css HTTP/1.1" 404 193 "https://domain.tld/flood/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3159.5 Safari/537.36"
IP - - [25/Jul/2017:23:38:29 +0200] "GET /flood/app.js HTTP/1.1" 404 193 "https://domain.tld/flood/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3159.5 Safari/537.36"
IP - - [25/Jul/2017:23:38:30 +0200] "GET /flood/app.js HTTP/1.1" 404 193 "https://domain.tld/flood/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3159.5 Safari/537.36"
```
With `location /whatever/` and `proxy_pass` all requests to `domain.tld/whatever` automatically get redirected to a path with the slash, so that's not the issue.
What else am I doing wrong?
